project:
  type: website

website:
  title: "Explore iNaturalist"
  navbar:
    left:
      - href: project-documentation.qmd
        text: Project Documentation
      - href: Accessing_data.qmd
        text: Data Cleaning
      - href: Data_Cleaning.qmd
        text: Data Cleaning
      - href: Data_Exploration.qmd
        text: Data Exploration
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
