---
title: "Set Up"
format: html
editor: visual
---

## Install Packages and Libraries

```{r}
# remotes::install_github("ropensci/rinat")
# remotes::install_github("ropensci/rgbif")
library(tidyverse)
library(rinat) # R package to retreive data from iNaturalist database
library(rgbif) # R package to retreive data from GBIF database
library(ggplot2) # R package for creating plots and maps
library(spData) # R package for importing US states data
library(sf) # R package for working with simple features
```

```{r}
# Access selected iNaturalist projects' observations using rinat::get_inat_obs_project()
# Assign data unique name
piedmont_obs <- get_inat_obs_project("maryland-master-naturalist-program-piedmont-region", type = "observations")
# Save data to local folder
readr::write_rds(piedmont_obs, here::here("data/piedmont_obs.rds"))

coastal_obs <- get_inat_obs_project("maryland-master-naturalist-program-coastal-plain", type = "observations")

readr::write_rds(coastal_obs, here::here("data/coastal_obs.rds"))

biodiv_obs <- get_inat_obs_project("biodiversity-of-maryland", type = "observations")

readr::write_rds(biodiv_obs, here::here("data/biodiv_obs.rds"))

data("us_states")
maryland_data <- dplyr::filter(us_states, NAME == "Maryland")

readr::write_rds(maryland_data, here::here("data/maryland_data.rds"))
```

```{r}
# Access iNaturalist data from GBIF using rgbif::occ_search()
#
# Recreate data occurance search done on website with the following filters:
#
# country or area = United States of America
# dataset = iNaturalist Research-grade Observations (50c9509d-22c7-4a22-a47d-8c48425ef4a7)
# has coordinate = true
# has geospatial issue = false
# occurance statis = present
# state province = Maryland

GBIF_MD_research_grade <-
  rgbif::occ_search(
    taxonKey = NULL,
    scientificName = NULL,
    country = "US",
    datasetKey = "50c9509d-22c7-4a22-a47d-8c48425ef4a7",
    hasCoordinate = TRUE,
    hasGeospatialIssue = FALSE,
    occurrenceStatus = "present",
    stateProvince = "Maryland"
  )
# Save data from search locally
readr::write_rds(GBIF_MD_research_grade, here::here("data/GBIF_MD_research_grade.rds"))
# Another example using occ_search
# This search includes the "year" parameter, where year is set to "2022"
GBIF_MD_research_grade_2022 <-
  rgbif::occ_search(
    taxonKey = NULL,
    scientificName = NULL,
    country = "US",
    datasetKey = "50c9509d-22c7-4a22-a47d-8c48425ef4a7",
    hasCoordinate = TRUE,
    hasGeospatialIssue = FALSE,
    occurrenceStatus = "present",
    stateProvince = "Maryland",
    year = "2022"
  )
```

```{r}
# Data can also be accessed from GBIF via downloading tsv files.
# The former method offers a glimpse at the dataset
# whereas downloading the csv provides the dataset in its entireity.
# NOTE: All GBIF data is in simple tab-separated values(TSV) format
#
# Read in GBIF data from csv using read_tsv()
GBIF_MD_research_grade_FULL <-
  readr::read_tsv("C:/Users/Kari/Documents/GitHub/exploreinaturalist/data/GBIF_MD_research_grade.csv")
```
