---
title: "Data Exploration"
editor: visual
---

```{r}
library(ggplot2)

```

```{r}
#Set up base map
data("us_states")
maryland_data <- filter(us_states, NAME == "Maryland")
maryland_map <-
  ggplot() +
  geom_sf(data = maryland_data, color = "black", fill = NA)
maryland_map
#Plot research grade data as layer on base map
#Coastal
coastal_research_map <- maryland_map +
  geom_sf(
    mapping = aes(),
    data = coastal_researchgrade) +
  labs(
    title = "Maryland Coastal Research Grade Observations",
    caption = "Data courtesy of iNaturalist: Master Naturalist Program - Coastal Plain \n project_id = 474")
coastal_research_map

#ADD THEME, TITLE, LABELS

#Piedmont
piedmont_research_map <- maryland_map +
  geom_sf(
    mapping = aes(),
    data = piedmont_researchgrade) +
  labs(
    title = "Maryland Piedmont Research Grade Observations",
    caption = "Data courtesy of iNaturalist: Master Naturalist Program - Piedmont Region \n project_id = 1396")
piedmont_research_map

#ADD THEME, TITLE, LABELS

#state biodiversity data
biodiv_researchgrade_map <- maryland_map +
  geom_sf(
    mapping = aes(),
    data = biodiv_researchgrade) +
  labs(
    title = "Maryland Biodiversity Research Grade Observations",
    caption = "Data courtesy of iNaturalist: Maryland Biodiversity Project \n project_id = 17241")
biodiv_researchgrade_map

#ADD THEME, TITLE, LABELS
```

```{r}
masternat_map <- maryland_map +
  geom_sf(
    mapping = aes(), color = "blue",
    data = coastal_researchgrade) +
  geom_sf(
    mapping = aes(), color = "red",
    data = piedmont_researchgrade) +
  geom_sf_label()
labs(
    title = "Maryland Masternaturalist Research Grade Observations",
    caption = "Data combined from piedmont and coastal regional projects")
  
masternat_map
```

```{r}
GBIF_kingdoms_map <- 
  ggplot(GBIF_sf) +
  geom_bar(mapping = aes(x = kingdom)) +
  labs(title = "Maryland Biodiversity by Kingdom")
GBIF_kingdoms_map

```

```{r}
MD_corvids<- GBIF_MD_research_grade_FULL %>%
  group_by(genus)%>%
  filter(family == "Corvidae")

MD_corvids_sf <-  sf::st_as_sf(MD_corvids, coords =c("decimalLongitude", "decimalLatitude"), crs = st_crs(4269))
  
# Of the 286 bird observations, 84 unique species have been reported in this dataset.

MD_corvids_bar <-
  ggplot(MD_corvids_sf, 
         aes(x = species)) +
  geom_bar() 

MD_corvids_bar
```
